# Site settings
author: Billy Adams
title: Why I chose data science
header-img: img/home-bg.png
email: william.adams120193@outlook.com
copyright_name: Billy Adams
description: > # this means to ignore newlines until "baseurl:"
  The plan
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  billyadm123

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
